### PR TITLE
OFFAPPS-538 Updated translations

### PR DESCRIPTION
**Pull request by ocke**
:koala:

Describe your PR

/cc @zendesk/quokka

### References
 - Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-538

### Risks
 - None

### CODE REVIEW

**Comment by pdeuter** [comment]
@ydrain  
Just wondering about these PRs: we haven't updated translations in quite awhile, so why are we making these PRs now?

**Comment by ydrain** [comment]
@pdeuter 

We've modified and added new languages a long time ago, but they are not included in the app. We've reported this issue, so I believe the app team is going to rebuild other official apps.

**Comment by ocke** [comment]
@ydrain

**Comment by ydrain** [comment]
cc: @injuhwang https://zendesk.atlassian.net/browse/LQA-157

**Pull request merged**
